from core.chopsticks import Chopsticks
from core.enums import Emotion, Intensity,Position, ServoConfig, Pose
import time



cs= Chopsticks()

cs.walk(num_steps=6,direction='front')
input("wow-------------------------------------")
cs.assume_pose(Pose.SIT_TALL.value)
input("wow")
cs.assume_pose(Pose.SIT_LOW.value)
input("wow")
cs.assume_pose(Pose.LIE_DOWN.value)
input("wow")
cs.assume_pose(Pose.BOW.value)
input("wow")
cs.assume_pose(Pose.STAND.value)
input("wow-------------------------------------")
cs.dance()
input("wow")
cs.say_yes_no("yes")
input("wow")
cs.say_yes_no("no")
input("wow-------------------------------------")

cs.show_emotion(Emotion.HAPPY.value)
input(Emotion.HAPPY.value)
cs.show_emotion(Emotion.SAD.value)
input(Emotion.HAPPY.value)
cs.show_emotion(Emotion.EXCITED.value)
input(Emotion.HAPPY.value)
cs.show_emotion(Emotion.CURIOUS.value)
input(Emotion.HAPPY.value)
cs.show_emotion(Emotion.SLEEPY.value)
input(Emotion.HAPPY.value)
cs.show_emotion(Emotion.LOVING.value)
input(Emotion.HAPPY.value)
cs.show_emotion(Emotion.GRUMPY.value)
input(Emotion.HAPPY.value)
cs.show_emotion(Emotion.SCARED.value)
input(Emotion.HAPPY.value)
cs.show_emotion(Emotion.MISCHIEVOUS.value)
input(Emotion.HAPPY.value)
cs.show_emotion(Emotion.NEUTRAL.value)
input(Emotion.HAPPY.value)
input("wow-------------------------------------")
cs.walk(num_steps=6,direction='back')
input("wow-------------------------------------")
